version: "3.8"
services:
  mysql:
    container_name: board-mysql
    build:
      dockerfile: Dockerfile
      context: ./mysql
    volumes:
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
      - ./mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: board
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_TCP_PORT: 3333
    restart: unless-stopped

  app:
    container_name: board-app
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - mysql
    restart: on-failure

  nginx:
    container_name: board-nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    links:
      - app
    depends_on:
      - app
    restart: always
