version: "3.8"
services:
  app:
    container_name: board-app
    build:
      dockerfile: Dockerfile.dev
      context: ./
    environment:
      HOST: ${HOST}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
    restart: on-failure

  nginx:
    container_name: board-nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    links:
      - app
    depends_on:
      - app
    restart: always
