spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  data:
    web:
      pageable:
        default-page-size: 30
        max-page-size: 100
        one-indexed-parameters: true

  profiles:
    include: oauth2

server:
  error:
    include-message: always
    whitelabel:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp:localhost/~/board
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://board-mysql:3333/board?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update