spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp:localhost/~/board
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  data:
    web:
      pageable:
        default-page-size: 30
        max-page-size: 100
        one-indexed-parameters: true

  profiles:
    include: oauth2

server:
  error:
    include-message: always
    whitelabel:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: local


  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true