spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  data:
    web:
      pageable:
        default-page-size: 30
        max-page-size: 100
        one-indexed-parameters: true

  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: id

        registration:
          google:
            client-id: 13554327060-2cm6tclp68q7sfnhu53iffpn10tvpra7.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://${HOST}/login/oauth2/code/google
            scope:
              - profile
              - email

          naver:
            client-id: 5VhQsSHxsvgEpUbCOq10
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: http://${HOST}/login/oauth2/code/naver
            authorization-grant-type: authorization_code

server:
  error:
    include-message: always
    whitelabel:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}/board
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
